### ISSUE TITLE
OpenAPI definition not created correctly if Output schema is a ZodArray

### ISSUE THREAD

**Issue by DoubleMalt** [JacobLinCool/sveltekit-api#43]
Eg. if in the api file Output is defined `export const Output = z.array(someZodSchema);` no response for the code 200 is generated.

However the output is validated correctly. As zod-to-openapi supports ZodArrays I think that should be fixable.

I'm happy to give it a stab if you point me to the right file to look at.

Other than that I'm super happy with your library!

**Comment by JacobLinCool** [comment]
I think it's something around here: https://github.com/JacobLinCool/sveltekit-api/blob/1d692170d90689e57073cd72e6a53fc063b295f6/src/lib/api.ts#L654-L655

Since an array in JavaScript is a type of object, perhaps my assumption here is incorrect.

**Comment by DoubleMalt** [comment]
Thanks for merging!
